package com.example.elyzareth.core.model

/**
 * Audit result generated by the Forensic Scanner module.
 * Evaluates watermarking, AI artifact markers, plagiarism/similarity scores, and stem integrity.
 */
data class ForensicScanReport(
    val scanId: String,
    val projectId: String,
    val scannedAssetHash: String,
    val scannedTimestamp: Long,
    val watermarkingStatus: WatermarkVerification,
    val similarityCheck: SimilarityResult,
    val aiArtifactDetectionScore: Float, // 0.0 to 1.0
    val audioIntegrityChecks: List<IntegrityCheckItem>,
    val passedAutomatedForensics: Boolean,
    val forensicExaminerSignOff: HumanSignOff? = null
)

enum class WatermarkVerification {
    ABSENT,
    DETECTED_VALID,
    TAMPERED_OR_CORRUPTED,
    NOT_APPLICABLE
}

data class SimilarityResult(
    val highestMatchPercent: Float,
    val matchedReferenceId: String?,
    val isWithinLegalClearanceThreshold: Boolean
)

data class IntegrityCheckItem(
    val checkName: String,
    val passed: Boolean,
    val details: String
)

data class HumanSignOff(
    val signatoryId: String,
    val signatoryRole: String,
    val signedAtTimestamp: Long,
    val remarks: String
)
